[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
todo_list_app = "584iRz9qDp4bgkSh15xAz37PSokmd5xUR8V1ueL9sm5J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dezzy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
